spring:
  datasource:
    url: jdbc:mysql://artoncoredb.cue52hua29pn.ap-northeast-2.rds.amazonaws.com:3306/artoncore?user=artonmaster
    username: artonmaster
    password: chaos0180
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: dev

server:
  port: 8082

JWT:
  ISSUER: TEST
  SECRET: H6J8GH4K9MJ7


cloud:
  aws:
    credentials:
        accessKey: AKIA4XTKVXFC4B4ZOG2X
        secretKey: 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
    stack:
      auto: false
    s3:
      bucket:
        name: arton-images-s3
        url: https://s3.ap-northeast-2.amazonaws.com/arton-images-s3/
    region:
      static: ap-northeast-2
