spring:
  datasource:
    url: jdbc:mysql://artoncoredb.cue52hua29pn.ap-northeast-2.rds.amazonaws.com:3306/artoncore?user=artonmaster
    username: artonmaster
    password: chaos0180
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: dev

server:
  port: 8082
