logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %thread [%-5level] %logger.%method:line%line - %msg%n"
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace