logging:
    pattern:
        file: "%d{HH:mm:ss.SSS} %thread [%-5level] %logger.%method:line%line - %msg%n"
        rolling-file-name: "/logs/batch.%d{yyyy-MM-dd}.%i"
    file:
        name: /logs/arton_core.log
        max-history: 30
    level:
        root: info
        org:
            springframework: debug