
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

name: Deploy Spring Boot to Amazon EC2

env:
  PROJECT_NAME: arton_core

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '16.0.2'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0.25'
          mysql database: 'artoncore'
          mysql user: 'artonmaster'
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://arton-deploy-s3/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name Arton-Deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name s3-arton-deploy --s3-location bucket=arton-deploy-s3,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
